### ISSUE TITLE
Doesn't install with pip

### ISSUE THREAD

**Issue by Peter-developer01** [wchistow/pystackapi#26]
I have ran command as follows in README.md:

```bash
$ pip3 install git+https://github.com/wchistow/pystackapi.git@0.1.1
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/wchistow/pystackapi.git@0.1.1
  Cloning https://github.com/wchistow/pystackapi.git (to revision 0.1.1) to /tmp/pip-req-build-ja3jv6jd
  Running command git clone --filter=blob:none --quiet https://github.com/wchistow/pystackapi.git /tmp/pip-req-build-ja3jv6jd
  Running command git checkout -q f74a5691a14a69002b1cb5499cd4e13188b9afc0
  Resolved https://github.com/wchistow/pystackapi.git to commit f74a5691a14a69002b1cb5499cd4e13188b9afc0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=1784 sha256=9293f5bd6d83c69da47c9f35c8bc606672306028e22856b1677874f052bddeee
  Stored in directory: /tmp/pip-ephem-wheel-cache-sinqhteh/wheels/15/86/f4/272b6c161e2247b212789bb8d018c011021861b34549cec540
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

Then ran `examples/users.py`:

```bash
$ python3 examples/users.py
```

And it shows:

```python
Traceback (most recent call last):
  File "/home/peter/Desktop/GitHub/wchistow/pystackapi/examples/users.py", line 1, in <module>
    from pystackapi import Site
ModuleNotFoundError: No module named 'pystackapi'
```

@nchistov @wchistow do either of you know how to fix that? I suppose the problem is somewhere in the pip configuration files or whatever. I'll try look at this but please do it too.

I'm using KDE neon if this matters.

**Comment by wchistow** [comment]
Hm, on my computer with Windows10 (Python - 3.11.5) all right:

```none
>pip3 install git+https://github.com/wchistow/pystackapi.git@0.1.1
Collecting git+https://github.com/wchistow/pystackapi.git@0.1.1
  Cloning https://github.com/wchistow/pystackapi.git (to revision 0.1.1) to c:\users\владимир\appdata\local\temp\pip-req-build-d5zq4qiz
  Running command git clone --filter=blob:none --quiet https://github.com/wchistow/pystackapi.git 'C:\Users\Владимир\AppData\Local\Temp\pip-req-build-d5zq4qiz'
  Running command git checkout -q f74a5691a14a69002b1cb5499cd4e13188b9afc0
  Resolved https://github.com/wchistow/pystackapi.git to commit f74a5691a14a69002b1cb5499cd4e13188b9afc0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests==2.31.0 in c:\python311\lib\site-packages (from pystackapi==0.1.1) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests==2.31.0->pystackapi==0.1.1) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests==2.31.0->pystackapi==0.1.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests==2.31.0->pystackapi==0.1.1) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests==2.31.0->pystackapi==0.1.1) (2023.7.22)
Building wheels for collected packages: pystackapi
  Building wheel for pystackapi (pyproject.toml) ... done
  Created wheel for pystackapi: filename=pystackapi-0.1.1-py3-none-any.whl size=14526 sha256=a32e91742a52843a97a1981da61fd976050209ed5db54bccf6a742034c373e42
  Stored in directory: C:\Users\Владимир\AppData\Local\Temp\pip-ephem-wheel-cache-lmlhgesy\wheels\ff\b4\0d\ba90a7b9c187623b1023f4ffb1cc18e932868b5bd87bfdd413
Successfully built pystackapi
Installing collected packages: pystackapi
  Attempting uninstall: pystackapi
    Found existing installation: pystackapi 0.1.0
    Uninstalling pystackapi-0.1.0:
      Successfully uninstalled pystackapi-0.1.0
Successfully installed pystackapi-0.1.1

>python
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pystackapi
>>> pystackapi.Site
<class 'pystackapi.site.Site'>
>>>
```

---

I found a similar issue on another project: https://github.com/lief-project/LIEF/issues/108.

They advise to upgrade the `setuptools` package (`pip3 install -U setuptools`). Maybe, this will help you.

**Comment by Peter-developer01** [comment]
@wchistow This didn't help either. I tried:

```none
peter@laptop:~$ pip install setuptools --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
Collecting setuptools
  Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
Installing collected packages: setuptools
Successfully installed setuptools-68.2.2
peter@laptop:~$ pip3 install git+https://github.com/wchistow/pystackapi.git@0.1.1
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/wchistow/pystackapi.git@0.1.1
  Cloning https://github.com/wchistow/pystackapi.git (to revision 0.1.1) to /tmp/pip-req-build-3usisyll
  Running command git clone --filter=blob:none --quiet https://github.com/wchistow/pystackapi.git /tmp/pip-req-build-3usisyll
  Running command git checkout -q f74a5691a14a69002b1cb5499cd4e13188b9afc0
  Resolved https://github.com/wchistow/pystackapi.git to commit f74a5691a14a69002b1cb5499cd4e13188b9afc0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
peter@laptop:~$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pystackapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pystackapi'
>>> 
```

**Comment by wchistow** [comment]
@Peter-developer01, maybe this can help you: https://stackoverflow.com/q/59997065

**Comment by Peter-developer01** [comment]
Will try later.

**Comment by Peter-developer01** [comment]
@wchistow Still no luck, sadly.

**Comment by wchistow** [comment]
@Peter-developer01, are other libraries installing successfully? If yes, it's the problem with this library, else, with your pip.

**Comment by Peter-developer01** [comment]
@wchistow yes, according to this, it's problem with the library.

```none
$ pip3 install tkinter-math
Defaulting to user installation because normal site-packages is not writeable
Collecting tkinter-math
  Downloading tkinter_math-0.2.4-py3-none-any.whl (7.8 kB)
Installing collected packages: tkinter-math
Successfully installed tkinter-math-0.2.4
$ 
```

**Comment by wchistow** [comment]
@Peter-developer01, what version of Python do you have?

**Comment by Peter-developer01** [comment]
@wchistow 

```none
$ python3 --version
Python 3.10.12
```

(TBH, you might notice this in my earlier messages)

**Comment by wchistow** [comment]
@Peter-developer01, maybe, this is something like your problem: https://github.com/pypa/setuptools/issues/3269?

**Comment by Peter-developer01** [comment]
Running `pip install --upgrade pip` and then `python3.10 -m pip install git+https://github.com/wchistow/pystackapi.git@0.1.1` helped me. Thanks for your support

**Comment by wchistow** [comment]
I'm glad you solved the problem.
